function MetadatosEnsayo = importfileMetadatos(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  METADATOSENSAYO = IMPORTFILEMETADATOS(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  METADATOSENSAYO = IMPORTFILEMETADATOS(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  MetadatosEnsayo = importfileMetadatos("/Users/luis/Documents/MATLAB/BG/input/metadatos/PD_ensayo_1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Sep-2021 20:30:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Variables", "Types", "Units", "Descriptions"];
opts.VariableTypes = ["string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Variables", "Types", "Units", "Descriptions"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Variables", "Types", "Units", "Descriptions"], "EmptyFieldRule", "auto");

% Import the data
MetadatosEnsayo = readtable(filename, opts);

end